import Layout from '../components/utils/layout'
import Head from 'next/head'
import Dashboard from '../components/dashboard'
import DataBokingHistory from '../components/table/databokinghistory'
export default function Home() {
  return (
    <>
      <Head>
        <title>Boking Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard />
        <DataBokingHistory />
      </Layout>
    </> 
  )
}
